### PR TITLE
Use __android_log_print for debug log on Android

### PR DESCRIPTION
**Pull request by codebylove**
Print log to Android system log for debug/assert messages

### CODE REVIEW

**Comment by codebylove** [comment]
I encountered tun2socks crashes, this update will help debug crashes on android.

**Comment by Mygod** [comment]
shadowsocks-android should automatically route stdout/stderr to logcat, no?

**Comment by madeye** [comment]
Yes, I don't think it's necessary.

**Comment by codebylove** [comment]
> Yes, I don't think it's necessary.

Have you tried this? I can't see abort log msg using printf. I can only see it after I changed to __android_log_print.

**Comment by codebylove** [comment]
Check [BLog.c](https://github.com/shadowsocks/badvpn/blob/4d7d40c7009828d816ac4b44b2600c6c9208faf5/base/BLog.c#L52)

**Comment by madeye** [comment]
Post your abort message here.

It can help us to reproduce your issue.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/e4382d9d26fa3c0608110ee51a9915691f9ad122/core/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt#L65-L72

Some legacy logging code was written before this change.

**Comment by codebylove** [comment]
> https://github.com/shadowsocks/shadowsocks-android/blob/e4382d9d26fa3c0608110ee51a9915691f9ad122/core/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt#L65-L72
> 
> Some legacy logging code was written before this change.

It's logged to crashlytics from the code.

**Pull request closed without merging**
