### PR TITLE
Log to corresponding android log level

### PR DESCRIPTION
**Pull request by codebylove**
All tun2socks logs are logged as android debug level, this is a fix for the log level.

### CODE REVIEW

**Comment by madeye** [comment]
@Mygod what do you think?

**Comment by codebylove** [comment]
I noticed the log level in [VpnService.kt](https://github.com/shadowsocks/shadowsocks-android/blob/ed26895b0894fece3b9b188bf4d22950605fe202/core/src/main/java/com/github/shadowsocks/bg/VpnService.kt#L211) is "warning"

**Review by Mygod — CHANGES_REQUESTED** [review]
`android_log_level_map` does not match with `level_names`.

**Comment by codebylove** [comment]
Android log level doesn't contain notice level, so I map it as warning. The first NULL name level may not happen, I map it to FATAL.

From NDK log.h
```
/**
 * Android log priority values, in increasing order of priority.
 */
typedef enum android_LogPriority {
  /** For internal use only.  */
  ANDROID_LOG_UNKNOWN = 0,
  /** The default priority, for internal use only.  */
  ANDROID_LOG_DEFAULT, /* only for SetMinPriority() */
  /** Verbose logging. Should typically be disabled for a release apk. */
  ANDROID_LOG_VERBOSE,
  /** Debug logging. Should typically be disabled for a release apk. */
  ANDROID_LOG_DEBUG,
  /** Informational logging. Should typically be disabled for a release apk. */
  ANDROID_LOG_INFO,
  /** Warning logging. For use with recoverable failures. */
  ANDROID_LOG_WARN,
  /** Error logging. For use with unrecoverable failures. */
  ANDROID_LOG_ERROR,
  /** Fatal logging. For use when aborting. */
  ANDROID_LOG_FATAL,
  /** For internal use only.  */
  ANDROID_LOG_SILENT, /* only for SetMinPriority(); must be last */
} android_LogPriority;
```

**Comment by Mygod** [comment]
I suggest map it to INFO.

**Comment by codebylove** [comment]
> I suggest map it to INFO.

Updated.

**Review by Mygod — APPROVED** [review]

**Comment by madeye** [comment]
Cool, thanks!

**Pull request merged**
